'"'+  '-'B'E'G'I'N':'"''
+ GLOW4:
+ </git checkout origin/main <file name>
+Run'' 'Runs::/Action::/:Build::/scripts::/Run-on :Runs :
+Runs :gh/pages :
+pages :edit "
+$ intuit install 
+PURL" --add-label "production"
+env:
+PR_URL: ${{github.event.pull_request.html_url}}
+GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+run: gh pr edit "$PR_URL" --add-label "production"
+env:
+PR_URL: ${{github.event.pull_request.html_url}}
+GITHUB_TOKEN: ${{ ((c)(r)).[12753750.[00]m]'_BITORE_34173.1337) ')]}}}'"'' :
+ </git checkout origin/main <file name>
blank_issues_enabled: false
contact_links:
  - name: GitHub Support
    url: https://support.github.com/contact
    about: Contact Support if you're having trouble with your GitHub account.
 19  
content/actions/quickstart.md → content/actions/build_script.yml
@@ -1,5 +1,20 @@
---	BEGIN
title: Quickstart for GitHub Actions	GLOW4
run::/Runs :
Runs :run::/Script::/:Build::/builds_Script :Actionscript..yml :
run::/Action::/:Build::/scripts::/Run-on :Runs :
+Runs :WORKSFLOW/GitHub/doc/package/javascript/README.md/.github/workflows/packages/javascripts/contributing.md/read.md :
+pages :edit "
+$ intuit install 
+PURL" --add-label "production"
+env:
+PR_URL: ${{github.event.pull_request.html_url}}
+GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+run: gh pr edit "$PR_URL" --add-label "production"
+env:
+PR_URL: ${{github.event.pull_request.html_url}}
+GITHUB_TOKEN: ${{ ((c)(r)).[12753750.[00]m]'_BITORE_34173.1337) ')]}}}'"'' :
+ </git checkout origin/main <file name>title: Quickstart for GitHub Actions
intro: 'Try out the features of {% data variables.product.prodname_actions %} in 5 minutes or less.'	intro: 'Try out the features of {% data variables.product.prodname_actions %} in 5 minutes or less.'
allowTitleToDifferFromFilename: true	allowTitleToDifferFromFilename: true
redirect_from:	redirect_from:
  - /actions/getting-started-with-github-actions/starting-with-preconfigured-workflow-templates	  - /actions/getting-started-with-github-actions/starting-with-preconfigured-workflow-templates
versions:	versions:
  fpt: '*'	  fpt: '*'
  ghes: '*'	  ghes: '*'
  ghae: '*'	  ghae: '*'
  ghec: '*'	  ghec: '*'
type: quick_start	type: quick_start
topics:	topics:
  - Fundamentals	  - Fundamentals
shortTitle: Quickstart	shortTitle: Quickstart
---	---
{% data reusables.actions.enterprise-beta %}	{% data reusables.actions.enterprise-beta %}
{% data reusables.actions.enterprise-github-hosted-runners %}	{% data reusables.actions.enterprise-github-hosted-runners %}
## Introduction	## Introduction
You only need a {% data variables.product.prodname_dotcom %} repository to create and run a {% data variables.product.prodname_actions %} workflow. In this guide, you'll add a workflow that demonstrates some of the essential features of {% data variables.product.prodname_actions %}. 	You only need a {% data variables.product.prodname_dotcom %} repository to create and run a {% data variables.product.prodname_actions %} workflow. In this guide, you'll add a workflow that demonstrates some of the essential features of {% data variables.product.prodname_actions %}. 
The following example shows you how {% data variables.product.prodname_actions %} jobs can be automatically triggered, where they run, and how they can interact with the code in your repository.	The following example shows you how {% data variables.product.prodname_actions %} jobs can be automatically triggered, where they run, and how they can interact with the code in your repository.
## Creating your first workflow	## Creating your first workflow
1. Create a `.github/workflows` directory in  your repository on {% data variables.product.prodname_dotcom %} if this directory does not already exist.	1. Create a `.github/workflows` directory in  your repository on {% data variables.product.prodname_dotcom %} if this directory does not already exist.
1. In the `.github/workflows` directory, create a file named `github-actions-demo.yml`. For more information, see "[Creating new files](/github/managing-files-in-a-repository/creating-new-files)."	1. In the `.github/workflows` directory, create a file named `github-actions-demo.yml`. For more information, see "[Creating new files](/github/managing-files-in-a-repository/creating-new-files)."
1. Copy the following YAML contents into the `github-actions-demo.yml` file:	1. Copy the following YAML contents into the `github-actions-demo.yml` file:
   ```yaml{:copy}	   ```yaml{:copy}
   name: GitHub Actions Demo	   name: GitHub Actions Demo
   {%- ifversion actions-run-name %}	   {%- ifversion actions-run-name %}
   run-name: {% raw %}${{ github.actor }}{% endraw %} is testing out GitHub Actions 🚀	   run-name: {% raw %}${{ github.actor }}{% endraw %} is testing out GitHub Actions 🚀
   {%- endif %}	   {%- endif %}
   on: [push]	   on: [push]
   jobs:	   jobs:
     Explore-GitHub-Actions:	     Explore-GitHub-Actions:
       runs-on: ubuntu-latest	       runs-on: ubuntu-latest
       steps:	       steps:
         - run: echo "🎉 The job was automatically triggered by a {% raw %}${{ github.event_name }}{% endraw %} event."	         - run: echo "🎉 The job was automatically triggered by a {% raw %}${{ github.event_name }}{% endraw %} event."
         - run: echo "🐧 This job is now running on a {% raw %}${{ runner.os }}{% endraw %} server hosted by GitHub!"	         - run: echo "🐧 This job is now running on a {% raw %}${{ runner.os }}{% endraw %} server hosted by GitHub!"
         - run: echo "🔎 The name of your branch is {% raw %}${{ github.ref }}{% endraw %} and your repository is {% raw %}${{ github.repository }}{% endraw %}."	         - run: echo "🔎 The name of your branch is {% raw %}${{ github.ref }}{% endraw %} and your repository is {% raw %}${{ github.repository }}{% endraw %}."
         - name: Check out repository code	         - name: Check out repository code
           uses: {% data reusables.actions.action-checkout %}	           uses: {% data reusables.actions.action-checkout %}
         - run: echo "💡 The {% raw %}${{ github.repository }}{% endraw %} repository has been cloned to the runner."	         - run: echo "💡 The {% raw %}${{ github.repository }}{% endraw %} repository has been cloned to the runner."
         - run: echo "🖥️ The workflow is now ready to test your code on the runner."	         - run: echo "🖥️ The workflow is now ready to test your code on the runner."
         - name: List files in the repository	         - name: List files in the repository
           run: |	           run: |
             ls {% raw %}${{ github.workspace }}{% endraw %}	             ls {% raw %}${{ github.workspace }}{% endraw %}
         - run: echo "🍏 This job's status is {% raw %}${{ job.status }}{% endraw %}."	         - run: echo "🍏 This job's status is {% raw %}${{ job.status }}{% endraw %}."
   ```	   ```
1. Scroll to the bottom of the page and select **Create a new branch for this commit and start a pull request**. Then, to create a pull request, click **Propose new file**.	1. Scroll to the bottom of the page and select **Create a new branch for this commit and start a pull request**. Then, to create a pull request, click **Propose new file**.
   ![Commit workflow file](/assets/images/help/repository/actions-quickstart-commit-new-file.png)	   ![Commit workflow file](/assets/images/help/repository/actions-quickstart-commit-new-file.png)
Committing the workflow file to a branch in your repository triggers the `push` event and runs your workflow.	Committing the workflow file to a branch in your repository triggers the `push` event and runs your workflow.
## Viewing your workflow results	## Viewing your workflow results
{% data reusables.repositories.navigate-to-repo %}	{% data reusables.repositories.navigate-to-repo %}
{% data reusables.repositories.actions-tab %}	{% data reusables.repositories.actions-tab %}
1. In the left sidebar, click the workflow you want to see.	1. In the left sidebar, click the workflow you want to see.
   ![Workflow list in left sidebar](/assets/images/help/repository/actions-quickstart-workflow-sidebar.png)	   ![Workflow list in left sidebar](/assets/images/help/repository/actions-quickstart-workflow-sidebar.png)
1. From the list of workflow runs, click the name of the run you want to see.	1. From the list of workflow runs, click the name of the run you want to see.
   ![Name of workflow run](/assets/images/help/repository/actions-quickstart-run-name.png)	   ![Name of workflow run](/assets/images/help/repository/actions-quickstart-run-name.png)
1. Under **Jobs** , click the **Explore-GitHub-Actions** job.	1. Under **Jobs** , click the **Explore-GitHub-Actions** job.
   ![Locate job](/assets/images/help/repository/actions-quickstart-job.png)	   ![Locate job](/assets/images/help/repository/actions-quickstart-job.png)
1. The log shows you how each of the steps was processed. Expand any of the steps to view its details.	1. The log shows you how each of the steps was processed. Expand any of the steps to view its details.
   ![Example workflow results](/assets/images/help/repository/actions-quickstart-logs.png)	   ![Example workflow results](/assets/images/help/repository/actions-quickstart-logs.png)
   	   
   For example, you can see the list of files in your repository:	   For example, you can see the list of files in your repository:
   ![Example action detail](/assets/images/help/repository/actions-quickstart-log-detail.png)	   ![Example action detail](/assets/images/help/repository/actions-quickstart-log-detail.png)
The example workflow you just added is triggered each time code is pushed to the branch, and shows you how {% data variables.product.prodname_actions %} can work with the contents of your repository. For an in-depth tutorial, see "[Understanding {% data variables.product.prodname_actions %}](/actions/learn-github-actions/understanding-github-actions)."	The example workflow you just added is triggered each time code is pushed to the branch, and shows you how {% data variables.product.prodname_actions %} can work with the contents of your repository. For an in-depth tutorial, see "[Understanding {% data variables.product.prodname_actions %}](/actions/learn-github-actions/understanding-github-actions)."
## More starter workflows	## More starter workflows
{% data reusables.actions.workflow-template-overview %}	{% data reusables.actions.workflow-template-overview %}
## Next steps	## Next steps
{% data reusables.actions.onboarding-next-steps %}	{% data reusables.actions.onboarding-next-steps %}
FooterzzBEGIN
GLOW4
run::/Runs :
Runs :run::/Script::/:Build::/builds_Script :Actionscript..yml :
run::/Action::/:Build::/scripts::/Run-on :Runs :
+Runs :WORKSFLOW/GitHub/doc/package/javascript/README.md/.github/workflows/packages/javascripts/contributing.md/read.md :
+pages :edit "
+$ intuit install 
+PURL" --add-label "production"
+env:
+PR_URL: ${{github.event.pull_request.html_url}}
+GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+run: gh pr edit "$PR_URL" --add-label "production"
+env:
+PR_URL: ${{github.event.pull_request.html_url}}
+GITHUB_TOKEN: ${{ ((c)(r)).[12753750.[00]m]'_BITORE_34173.1337) ')]}}}'"'' :
+ </git checkout origin/main <file name>title: Quickstart for GitHub Actions
intro: 'Try out the features of {% data variables.product.prodname_actions %} in 5 minutes or less.'
allowTitleToDifferFromFilename: true
redirect_from:
diff --git a/.husky/.gitignore b/.husky/.gitignore
deleted file mode 100644
index 31354ec1389..00000000000
--- a/.husky/.gitignore
+++ /dev/null
@@ -1 +0,0 @@
-_
diff --git a/.husly/.sh/bitore.sig b/.husly/.sh/bitore.sig
new file mode 100644
index 00000000000..e67f834feea
--- /dev/null
+++ b/.husly/.sh/bitore.sig
@@ -0,0 +1,16 @@
+ BEGIN:
+ GLOW4:
+ </git checkout origin/main <file name>
+Run'' 'Runs::/Action::/:Build::/scripts::/Run-on :Runs :
+Runs :gh/pages :
+pages :edit "
+$ intuit install 
+PURL" --add-label "production"
+env:
+PR_URL: ${{github.event.pull_request.html_url}}
+GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+run: gh pr edit "$PR_URL" --add-label "production"
+env:
+PR_URL: ${{github.event.pull_request.html_url}}
+GITHUB_TOKEN: ${{ ((c)(r)).[12753750.[00]m]'_BITORE_34173.1337) ')]}}}'"'' :
+ </git checkout origin/main <file name>
diff --git a/.husky/.gitignore b/.husky/.gitignore
deleted file mode 100644
index 31354ec1389..00000000000
--- a/.husky/.gitignore
+++ /dev/null
@@ -1 +0,0 @@
-_
diff --git a/.husly/.sh/bitore.sig b/.husly/.sh/bitore.sig
new file mode 100644
index 00000000000..e67f834feea
--- /dev/null
+++ b/.husly/.sh/bitore.sig
@@ -0,0 +1,16 @@
+ BEGIN:
+ GLOW4:
+ </git checkout origin/main <file name>
+Run'' 'Runs::/Action::/:Build::/scripts::/Run-on :Runs :
+Runs :gh/pages :
+pages :edit "
+$ intuit install 
+PURL" --add-label "production"
+env:
+PR_URL: ${{github.event.pull_request.html_url}}
+GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+run: gh pr edit "$PR_URL" --add-label "production"
+env:
+PR_URL: ${{github.event.pull_request.html_url}}
+GITHUB_TOKEN: ${{ ((c)(r)).[12753750.[00]m]'_BITORE_34173.1337) ')]}}}'"'' :
+ </git checkout origin/main <file name>
