# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
# See: https://circleci.com/docs/2.0/configuration-reference	
version: 2.1	version: 2.1


# Define a job to be invoked later in a workflow.	# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs	# See: https://circleci.com/docs/2.0/orb-intro/
jobs:	orbs:
  say-hello:	  node: circleci/node@4.7
