On :'Runs-on :::-on :''
'::-on :''
'     ·  
     ·  File by Mail Instructions for your 2021 Federal Tax Return
     ·  Important: Your taxes are not finished until all required steps are completed.
     ·  ZACHRY T WOOD
     ·  5222 Bradford Dr
     ·  Dallas, TX 75235-8313
     ·  Page 1 of 2
     ·  |
     ·  Balance | Your federal tax return (Form 1040) shows you owe a balance due of
     ·  Due/ | $257,567,263,607.00.
     ·  Refund |
     ·  | You are paying by check.
     ·  ______________________________________________________________________________________|
     ·  |
     ·  What You | Your tax return - The official return for mailing is included in
     ·  Need to | this printout. Remember to sign and date the return.
     ·  Mail |
     ·  | Your payment - Mail a check or money order for $257,567,263,607.00,
     ·  | payable to "United States Treasury". Write your Social Security
     ·  | number and "2021 Form 1040" on the check. Mail the return and check
     ·  | together.
     ·  |
     ·  | Attach the first copy or Copy B of Form(s) W-2 to the front of your
     ·  | Form 1040.
     ·  |
     ·  | Mail your return, attachments and payment to:
     ·  | Internal Revenue Service
     ·  | P.O. Box 1214
     ·  | Charlotte, NC 28201-1214
     ·  |
     ·  | Deadline: Postmarked by Monday, April 18, 2022
     ·  |
     ·  | Note: Your state return may be due on a different date. Please
     ·  | review your state filing instructions.
     ·  |
     ·  | Don't forget correct postage on the envelope.
     ·  ______________________________________________________________________________________|
     ·  |
     ·  What You | Keep these instructions and a copy of your return for your records.
     ·  Need to | You can download or print a copy of your return by logging into your
     ·  Keep | TurboTax account.
     ·  ______________________________________________________________________________________|
     ·  |
     ·  2021 | Adjusted Gross Income                   $    999,999.00
     ·  Federal | Taxable Income                          $    689,999.00
     ·  Tax | Total Tax                               257,637,118,600.00
     ·  Return | Total Payments/Credits                  $ 69,854,993.00
     ·  Summary | Payment Due                             257,567,263,607.00
     ·  | Effective Tax Rate                               0.00%
     ·  ______________________________________________________________________________________|
     ·  
     ·  File by Mail Instructions for your 2021 Federal Tax Return
     ·  Important: Your taxes are not finished until all required steps are completed.
     ·  ZACHRY T WOOD
     ·  5222 Bradford Dr
     ·  Dallas, TX 75235-8313
     ·  Page 2 of 2
     ·  |
     ·  Estimated | Estimated Payments for 2022 - Do not mail these vouchers with your
     ·  Payments to | 2021 income tax return. The estimated vouchers displayed below are
     ·  Make for Next | used to prepay your 2022 income taxes that will be filed next year.
     ·  Year's Return | If you expect to owe more than $1,000 in 2022, you may incur
     ·  | underpayment penalties if you do not make these four estimated tax
     ·  | payments. This printout includes your estimated tax vouchers for your
     ·  | federal estimated taxes (Form 1040-ES).
     ·  |
     ·  | Mail payments according to the schedule below:
     ·  |
     ·  |       Voucher Number        Due Date                Amount
     ·  |             1                04/18/2022           70,842,743,866.00
     ·  |             2                06/15/2022           70,842,743,866.00
     ·  |             3                09/15/2022           70,842,743,866.00
     ·  |             4                01/17/2023           70,842,743,866.00
     ·  |
     ·  | Include a separate check or money order for each payment, payable to
     ·  | "United States Treasury". Write your social security number and "Form
     ·  | 1040-ES" on each check.
     ·  |
     ·  | Mail payments to:
     ·  | Internal Revenue Service
     ·  | P.O. Box 1300
     ·  | Charlotte, NC 28201-1300
     ·  ______________________________________________________________________________________|
     ·  
     ·        Form 1040-ES Payment Voucher
     ·  II
     ·  Detach Here and Mail With Your Payment
     ·  Department of the Treasury
     ·  Calendar Year 
     ·  '
     ·  Internal Revenue Service
     ·  Due 
     ·  File only if you are making a payment of estimated tax by check or money order. Mail this
     ·  Amount of estimated tax
     ·  voucher with your check or money order payable to the 'United States Treasury.' Write your
     ·  you are paying by check
     ·  social security number and '        Form 1040-ES' on your check or money order. Do not send
     ·  G
     ·  cash. Enclose, but do not staple or attach, your payment with this voucher.
     ·  or money order
     ·  . . . . . . . . . . 
     ·  1
     ·  DALLAS TX 75235-8313
     ·  70,842,743,866.
     ·  5222 BRADFORD DR
     ·  633-44-1725
     ·  INTERNAL REVENUE SERVICE
     ·  PO BOX 1300
     ·  CHARLOTTE NC 28201-1300
     ·  04/18/2022
     ·  2022
     ·  2022
     ·  REV 04/09/22 INTUIT.CG.CFP.SP
     ·  1555
     ·  ZACHRY T WOOD
     ·  633441725 BH WOOD 30 0 202212 430
''
  # The advantage of 'pull_request' over 'pull_request_target' is that we
  # can make changes to this file and test them in a pull request, instead
  # of relying on landing it in 'main' first.
  # From a security point of view, its arguably safer this way because
  # unlike 'pull_request_target', these only have secrets if the pull
  # request creator has permission to access secrets.
  pull_request_target:
  merge_group:
  workflow_dispatch:
    inputs:
      PR_NUMBER:
        description: 'PR Number'
        type: string
        required: true
      COMMIT_REF:
        description: 'The commit SHA to build'
        type: string
        required: true

permissions:
  contents: read
  deployments: write

# This allows one deploy workflow to interrupt another
concurrency:
  group: 'preview-env @ ${{ github.head_ref || github.run_id }} for ${{ github.event.number || github.event.inputs.PR_NUMBER }}'
  cancel-in-progress: true

jobs:
  build-and-deploy-azure-preview:
    name: Build and deploy Azure preview environment
    runs-on: ubuntu-latest
    # Ensure this is actually a pull request and not a merge group
    # If its a merge group, report success without doing anything
    # See https://bit.ly/3qB9nZW > If a job in a workflow is skipped due to a conditional, it will report its status as "Success".
    if: ((github.event.pull_request.head.sha || github.event.inputs.COMMIT_REF) && (github.event.number || github.event.inputs.PR_NUMBER || github.run_id)) && (github.repository == 'github/docs-internal' || github.repository == 'github/docs')
    timeout-minutes: 15
    environment:
      name: preview-env-${{ github.event.number }}
      # The environment variable is computer later in this job in
      # the "Get preview app info" step.
      # That script sets environment variables which is used by Actions
      # to link a PR to a list of environments later.
      url: ${{ env.APP_URL }}
    env:
      PR_NUMBER: ${{ github.event.number || github.event.inputs.PR_NUMBER || github.run_id }}
      COMMIT_REF: ${{ github.event.pull_request.head.sha || github.event.inputs.COMMIT_REF }}
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
      IS_INTERNAL_BUILD: ${{ github.repository == 'github/docs-internal' }}
      # This may also run in forked repositories, not just 'github/docs'
      IS_PUBLIC_BUILD: ${{ github.repository != 'github/docs-internal' }}
      NONPROD_REGISTRY_USERNAME: ${{ fromJSON('["ghdocs", "ghdocsinternal"]')[github.repository == 'github/docs-internal'] }}

    steps:
      - name: 'Az CLI login'
        uses: azure/login@1f63701bf3e6892515f1b7ce2d2bf1708b46beaf
        with:
          creds: ${{ secrets.NONPROD_AZURE_CREDENTIALS }}

      - name: 'Docker login'
        uses: azure/docker-login@83efeb77770c98b620c73055fbb59b2847e17dc0
        with:
          login-server: ${{ secrets.NONPROD_REGISTRY_SERVER }}
          username: ${{ env.NONPROD_REGISTRY_USERNAME }}
          password: ${{ secrets.NONPROD_REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@95cb08cb2672c73d4ffd2f422e6d11953d2a9c70

      - if: ${{ env.IS_PUBLIC_BUILD == 'true' }}
        name: Check out main branch
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          ref: 'main'
          persist-credentials: 'false'
          lfs: 'true'

      - if: ${{ env.IS_INTERNAL_BUILD == 'true' }}
        name: Check out PR code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          ref: ${{ env.COMMIT_REF }}
          # To prevent issues with cloning early access content later
          persist-credentials: 'false'
          lfs: 'true'

      - name: Check out LFS objects
        run: git lfs checkout

      - name: Get preview app info
        env:
          APP_NAME_SEED: ${{ secrets.PREVIEW_ENV_NAME_SEED }}
        run: .github/actions-scripts/get-preview-app-info.sh

      - name: 'Set env vars'
        run: |
          # Image tag is unique to each workflow run so that it always triggers a new deployment
          echo "DOCKER_IMAGE=${{ secrets.NONPROD_REGISTRY_SERVER }}/${IMAGE_REPO}:${{ env.COMMIT_REF }}-${{ github.run_number }}-${{ github.run_attempt }}" >> $GITHUB_ENV

      - if: ${{ env.IS_INTERNAL_BUILD == 'true' }}
        name: Determine which docs-early-access branch to clone
        id: 'check-early-access'
        uses: actions/github-script@2b34a689ec86a68d8ab9478298f91d5401337b7d
        env:
          BRANCH_NAME: ${{ env.BRANCH_NAME }}
        with:
          github-token: ${{ secrets.DOCUBOT_REPO_PAT }}
          result-encoding: string
          script: |
            const { BRANCH_NAME } = process.env

            try {
              const { status } = await github.request('GET /repos/{owner}/{repo}/branches/{branch}', {
                owner: 'github',
                repo: 'docs-early-access',
                branch: BRANCH_NAME,
              })

              if (status !== 200) {
                throw new Error('Received non-200 response from branch GET request')
              }

              console.log(`Using docs-early-access branch '${BRANCH_NAME}'`)
              return BRANCH_NAME
            } catch (e) {
              console.log(`Failed to get docs-early-access branch '${BRANCH_NAME}', 'main' will be used instead.`)
              return 'main'
            }

      - if: ${{ env.IS_INTERNAL_BUILD == 'true' }}
        name: Clone docs-early-access
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          repository: github/docs-early-access
          token: ${{ secrets.DOCUBOT_REPO_PAT }}
          path: docs-early-access
          ref: ${{ steps.check-early-access.outputs.result }}

      - if: ${{ env.IS_INTERNAL_BUILD == 'true' }}
        name: Merge docs-early-access repo's folders
        run: .github/actions-scripts/merge-early-access.sh

      - if: ${{ env.IS_PUBLIC_BUILD == 'true' }}
        name: Check out user code to temp directory
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          path: ./user-code
          ref: ${{ env.COMMIT_REF }}

      # Move acceptable user changes into our main branch checkout
      - if: ${{ env.IS_PUBLIC_BUILD == 'true' }}
        name: Move acceptable user changes
        run: |
          # Make sure recursive path expansion is enabled
          shopt -s globstar
          rsync -rptovR ./user-code/content/./**/*.md ./content
          rsync -rptovR ./user-code/assets/./**/*.png ./assets
          rsync -rptovR ./user-code/data/./**/*.{yml,md} ./data
          rsync -rptovR ./user-code/components/./**/*.{scss,ts,tsx} ./components
          rsync -rptovR --ignore-missing-args ./user-code/lib/./**/*.{js,ts} ./lib
          rsync -rptovR --ignore-missing-args ./user-code/middleware/./**/*.{js,ts} ./middleware
          rsync -rptovR ./user-code/pages/./**/*.tsx ./pages
          rsync -rptovR ./user-code/stylesheets/./**/*.scss ./stylesheets

      # In addition to making the final image smaller, we also save time by not sending unnecessary files to the docker build context
      - name: 'Prune for preview env'
        run: .github/actions-scripts/prune-for-preview-env.sh

      - name: 'Build and push image'
        uses: docker/build-push-action@1cb9d22b932e4832bb29793b7777ec860fc1cde0
        with:
          context: .
          push: true
          target: preview
          tags: ${{ env.DOCKER_IMAGE }}
          # we only pull the `main` cache image
          cache-from: type=registry,ref=${{ secrets.NONPROD_REGISTRY_SERVER }}/${{ github.repository }}:main-preview
          # `main-docker-cache.yml` handles updating the remote cache so we don't pollute it with PR specific code
          cache-to: ''
          build-args: |
            BUILD_SHA=${{ env.COMMIT_REF }}

      # Succeed despite any non-zero exit code (e.g. if there is no deployment to cancel)
      - name: 'Cancel any existing deployments for this PR'
        run: |
          az deployment group cancel --name ${{ env.DEPLOYMENT_NAME }} -g ${{ secrets.PREVIEW_ENV_RESOURCE_GROUP }} || true

      # Deploy ARM template is idempotent
      # Note: once the resources exist the image tag must change for a new deployment to occur (the image tag includes workflow run number, run attempt, as well as sha)
      - name: Run ARM deploy
        uses: azure/arm-deploy@841b12551939c88af8f6df767c24c38a5620fd0d
        with:
          resourceGroupName: ${{ secrets.PREVIEW_ENV_RESOURCE_GROUP }}
          subscriptionId: ${{ secrets.NONPROD_SUBSCRIPTION_ID }}
          template: ./azure-preview-env-template.json
          deploymentName: ${{ env.DEPLOYMENT_NAME }}
          parameters: appName="${{ env.APP_NAME }}"
            containerImage="${{ env.DOCKER_IMAGE }}"
            dockerRegistryUrl="${{ secrets.NONPROD_REGISTRY_SERVER }}"
            dockerRegistryUsername="${{ env.NONPROD_REGISTRY_USERNAME }}"
            dockerRegistryPassword="${{ secrets.NONPROD_REGISTRY_PASSWORD }}"

      - name: Check that it can reached
        # This introduces a necessary delay. Because the preview evironment
        # URL is announced to the pull request as soon as all the steps
        # finish, what sometimes happens is that a viewer of the PR clicks
        # that link too fast and are confronted with a broken page.
        # It's because there's a delay between the `azure/arm-deploy`
        # and when the server is actually started and can receive and
        # process requests.
        # By introducing a slight "delay" here we avoid announcing a
        # preview environment URL that isn't actually working just yet.
        run: curl --retry-connrefused --retry 5 -I ${{ env.APP_URL }}
