name: NodeJS with Grunt
on:
  push:
    branches: [ "Main.yml" ]
  pull_request:
    branches: [ "Main.yml" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: |
        npm install JPMORGAN TRUST I																									
Paycheck history report																									
																									
Paychecks from Mar 17, 2023 to Mar 17, 2023 for all employees from all locations																									
Pay date	Name	Total pay	Net pay	Pay method	Check Number	Status																			
03/17/2023	Wood, Zack null	$ 22,679,572,368,607.00	$ 22,679,570,023,683.40	Check	881303491	-																			
03/17/2023	Wood, Zack null	$ 22,679,572,368,607.00	$ 22,679,570,015,551.00	Check	101	-																			
Thursday, March 16, 2023 11:13 PM GMT-05:00 1/2																									
INTU																									
1099 Transaction Detail Report																									
January - December 2022																									
DATE TRANSACTION TYPE NUM MEMO/DESCRIPTION 1099 BOX ACCOUNT SPLIT AMOUNT BALANCE TAX ID																									
  ::  Note  :::																									
Back to report list																									
1099 Transaction Detail Report																									
Report period																									
01/01/2022																									
to																									
12/31/2022																									
Accounting method																									
Cash Accrual																									
Filters: Payment TypeVendor																									
Edit notes																									
3/6/22, 5:44 PM EIN: 77-0034661 INCOME STATEMENT FROM MAR 17, 20																									
1099 Transaction Detail Report																									
January - December 2022																									
This report does not contain any data.																									
Deductions and Contributions Report																									
From Mar 17, 2023 to Mar 17, 2023																									
Description Type Employee deductions Company contributions Plan total																									
Medicare Tax Withheld Wage Garnishment $ 118,167.00 $ 0.00 $ 118,167.00																									
Social Security Tax Withheld Wage Garnishment $ 8,537.00 $ 0.00 $ 8,537.00																									
Total $ 126,704.00 $ 0.00 $ 126,704.00																									
Part I | Reporting Issuer																									
1. Issuer's Identity.																									
Payor :																									
INTUIT INC EMPLOYER IDENTIFICATION NUMBER (EIN) :77-0034661																									
2700 COAST AVENUE MOUNTAIN VIEW CALIFORNA 94043																									
All Dates																									
Wednesday, March 15, 2023 03:38 AM GMT-05:00 1/1																									
DATE TRANSACTION TYPE NUM ADJ NAME MEMO/DESCRIPTION ACCOUNT DEBIT CREDIT																									
03/17/2023 Payroll Check 519 No ZACHRY T. WOOD Pay Period: 03/09/2023-03/15/2023 Employer :																									
Employer Identification Number (EIN): XXXXX4661																									
INTU																									
2700 C																									
Employee :																									
Employee's Social Security Number : XXX-XX-1725																									
ZACH T WOO																									
5222 B																									
Payer :																									
Payer's Federal Identification Number (FIN) : XXXXX4775																									
THE																									
101 EA																									
Business Checking $3,088,762.10																									
No Gross Pay - This is not a legal pay stub Payroll Expenses:Wages $5,105,000.00																									
No Employer Taxes Payroll Expenses:Taxes $84,566.60																									
No TX Unemployment Tax Payroll Liabilities:TX Unemployment Tax $569.70																									
No Federal Unemployment (940) Payroll Liabilities:Federal Unemployment (940) $42.00																									
No Federal Taxes (941/943/944) Payroll Liabilities:Federal Taxes (941/943/944) $2,100,192.80																									
$5,189,566.60 $5,189,566.60																									
Thursday, March 16, 2023 11:13 PM GMT-05:00 1/2																									
INTU																									
1099 Transaction Detail Report																									
January - December 2022																									
DATE TRANSACTION TYPE NUM MEMO/DESCRIPTION 1099 BOX ACCOUNT SPLIT AMOUNT BALANCE TAX ID																									
Note																									
Back to report list																									
1099 Transaction Detail Report																									
Report period																									
01/01/2022																									
to																									
12/31/2022																									
Accounting method																									
Cash Accrual																									
Filters: Payment TypeVendor																									
Edit notes																									
3/6/22, 5:44 PM EIN: 77-0034661 INCOME STATEMENT FROM MAR 17, 20																									
1099 Transaction Detail Report																									
January - December 2022																									
This report does not contain any data.																									
Deductions and Contributions Report																									
From Mar 17, 2023 to Mar 17, 2023																									
Description Type Employee deductions Company contributions Plan total																									
Medicare Tax Withheld Wage Garnishment $ 118,167.00 $ 0.00 $ 118,167.00																									
Social Security Tax Withheld Wage Garnishment $ 8,537.00 $ 0.00 $ 8,537.00																									
Total $ 126,704.00 $ 0.00 $ 126,704.00																									
Part I | Reporting Issuer																									
1. Issuer's Identity.																									
Payor :																									
INTUIT INC EMPLOYER IDENTIFICATION NUMBER (EIN) :77-0034661																									
2700 COAST AVENUE MOUNTAIN VIEW CALIFORNA 94043																									
All Dates																									
Wednesday, March 15, 2023 03:38 AM GMT-05:00 1/1																									
DATE TRANSACTION TYPE NUM ADJ NAME MEMO/DESCRIPTION ACCOUNT DEBIT CREDIT																									
03/17/2023 Payroll Check 519 No ZACHRY T. WOOD Pay Period: 03/09/2023-03/15/2023 Employer :																									
Employer Identification Number (EIN): XXXXX4661																									
INTU																									
2700 C																									
Employee :																									
Employee's Social Security Number : XXX-XX-1725																									
ZACH T WOO																									
5222 B																									
Payer :																									
Payer's Federal Identification Number (FIN) : XXXXX4775																									
THE																									
101 EA																									
Business Checking $3,088,762.10																									
No Gross Pay - This is not a legal pay stub Payroll Expenses:Wages $5,105,000.00																									
No Employer Taxes Payroll Expenses:Taxes $84,566.60																									
No TX Unemployment Tax Payroll Liabilities:TX Unemployment Tax $569.70																									
No Federal Unemployment (940) Payroll Liabilities:Federal Unemployment (940) $42.00																									
No Federal Taxes (941/943/944) Payroll Liabilities:Federal Taxes (941/943/944) $2,100,192.80																									
$5,189,566.60 $5,189,566.60																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
																									
        grunt
