name: Triage new pull requests

# **What it does**: Adds triage label to new pull requests in the open source repository.
# **Why we have it**: Update project board for new pull requests for triage.
# **Who does it impact**: Docs open source.

on:
  pull_request_target:
    types:
      - reopened
      - opened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  triage_pulls:
    if: ${{ github.repository == 'github/docs' }}
    runs-on: ubuntu-latest

    steps:
      - name: Label new pull requests with 'triage'
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: 'triage'

      - name: Check out repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: ./.github/actions/slack-alert
        with:
          slack_channel_id: ${{ secrets.DOCS_ALERTS_SLACK_CHANNEL_ID }}
          slack_token: ${{ secrets.SLACK_DOCS_BOT_TOKEN }}
